input_vars:
 - name: reparse

seeder:
  file: "./seeder/seeder.rb"
  disabled: false

parsers:
  - page_type: listings
    file: "./parsers/listings.rb"
    disabled: false
  - page_type: listing_html
    file: "./parsers/listing_html.rb"
    disabled: false
  - page_type: product_html
    file: "./parsers/product_html.rb"
    disabled: false
  - page_type: products
    file: "./parsers/products.rb"
    disabled: false
  - page_type: product
    file: "./parsers/products.rb"
    disabled: false
  - page_type: barcode
    file: "./parsers/barcode.rb"
    disabled: false
  - page_type: rating
    file: "./parsers/rating.rb"
    disabled: false
  - page_type: categories
    file: "./parsers/categories.rb"
    disabled: false

finisher:
  file: "./finisher/finisher.rb"
  disabled: false

exporters:
  - file: "./exporters/product_json.yaml"
    disabled: false
  - file: "./exporters/product_csv.yaml"
    disabled: false
    
parse_failed_pages: true
